[package]
name = "challenge6"
version = "0.0.1"
authors = ["Tim Taubert <tim@timtaubert.de>"]

[dependencies.challenge1]
path = "../challenge1"

[dependencies.challenge3]
path = "../challenge3"

[dependencies.challenge4]
path = "../challenge4"

[dependencies.challenge5]
path = "../challenge5"
