[package]
name = "challenge24"
version = "0.0.1"
authors = ["Tim Taubert <tim@timtaubert.de>"]

[dependencies.challenge2]
path = "../challenge2"

[dependencies.challenge21]
path = "../challenge21"

[dependencies.challenge22]
path = "../challenge22"

[dependencies.rand]
rand = "0.3"
