[package]
name = "challenge18"
version = "0.0.1"
authors = ["Tim Taubert <tim@timtaubert.de>"]

[dependencies.challenge2]
path = "../challenge2"

[dependencies.challenge6]
path = "../challenge6"

[dependencies.challenge10]
path = "../challenge10"
